format = 'ğŸš€ $directory $git_branch '
style = 'bold green'
add_newline = false
right_format = '$nodejs'

[git_branch]
format='[$symbol$branch]($style)'
symbol='î‚  '
style='bold purple'

[nodejs]
format = '[îœ˜  $version](bold green) '
detect_files=['package.json']
#
# [battery]
# full_symbol = 'ğŸ”‹ '
# charging_symbol = 'âš¡ï¸ '
# discharging_symbol = 'ğŸ’€ '
#
# [[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
# threshold = 10
# style = 'bold red'
#
# [[battery.display]] # 'bold yellow' style and ğŸ’¦ symbol when capacity is between 10% and 30%
# threshold = 30
# style = 'bold yellow'
# discharging_symbol = 'ğŸ’¦'
#
# [[battery.display]] # 'bold yellow' style and ğŸ’¦ symbol when capacity is between 10% and 30%
# threshold = 100
# style = 'bold green'
# discharging_symbol = 'ğŸ”‹'
#
#
#
